# Generated by Django 4.1 on 2022-09-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
                ('Content', models.TextField()),
            ],
        ),
    ]
