# Generated by Django 4.1 on 2022-10-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=200)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Subject', models.TextField()),
                ('Your_Message', models.TextField()),
            ],
        ),
    ]
